name: Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - run: |
          dotnet test
